stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    # Submission
    server {
        listen mail-relay.ruconet.internal:587 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:587;
        proxy_timeout 30m;
    }
}
