stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    map $ssl_client_s_dn $ruconet_source {
        "CN=mail.ruconet.internal" 127.0.0.5;
        default                    "";
    }

    # Submission
    server {
        listen mail-relay.ruconet.internal:587 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:587;
        proxy_bind $ruconet_source;
        proxy_timeout 30m;
    }
}
